FROM nginx:stable-alpine

# Essentials
RUN echo "UTC" > /etc/timezone
RUN apk add --no-cache nano

# Add certbot
RUN apk add --no-cache certbot certbot-nginx

# Change work directory
WORKDIR /etc/nginx

# Copy to docker
COPY nginx.conf /etc/nginx/nginx.conf
COPY common.conf /etc/nginx/common.conf
COPY common_location.conf /etc/nginx/common_location.conf
COPY ssl.conf /etc/nginx/ssl.conf
