version: "3.7"
services:
  backend:
    image: yanuadin/app-antrian-sehat-backend-prod:latest
    container_name: antrian_sehat-backend
    restart: unless-stopped
    working_dir: /var/www/antrian-sehat-backend
    env_file: ".env"
    labels: 
      - traefik.http.routers.backend.rule=Host(`api.antrian-sehat.me`)
      - traefik.http.routers.backend.tls=true
      - traefik.http.routers.backend.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - antrian_sehat

  frontend:
    image: yanuadin/app-antrian-sehat-frontend:1.1
    container_name: antrian_sehat-frontend
    restart: unless-stopped
    working_dir: /var/www/antrian-sehat-frontend
    labels: 
      - traefik.http.routers.frontend.rule=Host(`www.antrian-sehat.me`, `antrian-sehat.me`)
      - traefik.http.routers.frontend.tls=true
      - traefik.http.routers.frontend.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - antrian_sehat

  mysql:
    image: mysql:5.7.31
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports: 
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql
    labels:
      - traefik.enable=false
    networks:
      - antrian_sehat

  traefik:
    image: traefik:v2.3
    restart: unless-stopped
    ports: 
      - "80:80"
      - "443:443"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/acme.json
    command:
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesResolvers.lets-encrypt.acme.email=yanu30adi@gmail.com"
      - "--certificatesResolvers.lets-encrypt.acme.storage=acme.json"
      - "--certificatesResolvers.lets-encrypt.acme.tlsChallenge=true"
    networks:
      - antrian_sehat

volumes:
  mysql-data:
    driver: local

networks:
  antrian_sehat:
    name : antrian_sehat