version: "3.7"
services:
  backend:
    image: yanuadin/app-antrian-sehat-backend-prod:latest
    container_name: antrian_sehat-backend
    restart: unless-stopped
    working_dir: /var/www/antrian-sehat-backend
    env_file: ".env"
    networks:
      - antrian_sehat

  frontend:
    image: yanuadin/app-antrian-sehat-frontend:latest
    container_name: antrian_sehat-frontend
    restart: unless-stopped
    working_dir: /var/www/antrian-sehat-frontend
    networks:
      - antrian_sehat

  mysql:
    image: mysql:5.7.31
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports: 
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - antrian_sehat

  nginx:
    image: yanuadin/nginx-router:latest
    container_name: nginx
    restart: unless-stopped
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - antrian_sehat

volumes:
  mysql-data:
    driver: local

networks:
  antrian_sehat:
    name : antrian_sehat