version: "3.7"
services:
  backend:
    image: yanuadin/app-antrian-sehat:1.3
    container_name: antrian_sehat-app
    restart: unless-stopped
    working_dir: /var/www/antrian-sehat-backend
    volumes:
      - ./.env:/var/www/antrian-sehat-backend/.env
    networks:
      - antrian_sehat

  frontend:
    image: yanuadin/app-antrian-sehat-frontend:1.0
    working_dir: /var/www/antrian-sehat-frontend
    restart: unless-stopped
    working_dir: /var/www/antrian-sehat-frontend
    ports:
      - 3000:80
    networks:
      - antrian_sehat

  mysql:
    image: mysql:8.0.21
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports: 
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - antrian_sehat

  nginx:
    image: jwilder/nginx-proxy:0.7.0
    restart: unless-stopped
    ports: 
      - "80:80"
      - "443:443"
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/nginx-proxy.conf:ro
    networks:
      - antrian_sehat

volumes:
  mysql-data:
    driver: local

networks:
  antrian_sehat:
    name : antrian_sehat